version: "3"

services:
  telegram_ai_chatbot:
    environment:
      - MONGODB_URI=${MONGODB_URI:?error}
      - MONGODB_DATABASE=${MONGODB_DATABASE:-telegram-ai-chatbot}
      - TELEGRAM_BOT_NAME=${TELEGRAM_BOT_NAME}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:?error}
      - DEFAULT_MODEL=${DEFAULT_MODEL}
      - ENABLE_SELECT_MODEL=${ENABLE_SELECT_MODEL}
      - ENABLE_CUSTOM_ROLE=${ENABLE_CUSTOM_ROLE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_CHAT_API_TYPE=${OPENAI_CHAT_API_TYPE}
      - CGP_PROJECT_ID=${CGP_PROJECT_ID}
      - AZURE_OPENAI_API_BASE=${AZURE_OPENAI_API_BASE}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - COQUI_STUDIO_TOKEN=${COQUI_STUDIO_TOKEN}
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
      - GETIMG_API_TOKEN=${GETIMG_API_TOKEN}
      - SINKIN_ACCOUNT=${SINKIN_ACCOUNT}
      - ALLOWED_TELEGRAM_USERNAMES=${ALLOWED_TELEGRAM_USERNAMES}
      - DEFAULT_CHAT_TIMEOUT=${DEFAULT_CHAT_TIMEOUT}
      - FREE_QUOTA=${FREE_QUOTA}
      - DALLE_TOKENS=${DALLE_TOKENS}
      - TOKEN_PRICE=${TOKEN_PRICE}
      - GPT_PROMPTS=${GPT_PROMPTS}
      - TTS_MODELS=${TTS_MODELS}
      - WEB_APP_URL=${WEB_APP_URL}
      - BUGREPORT_BOT_TOKEN=${BUGREPORT_BOT_TOKEN}
      - BUGREPORT_CHAT_ID=${BUGREPORT_CHAT_ID}
    restart: always
    build:
      context: "."
    volumes:
      - ${GCP_KEY:-.gcp_key.json}:/.gcp_key.json
